CREATE TABLE AIRLINES (
	CODE CHAR(2) NOT NULL,
    NAME VARCHAR(20) NOT NULL,
    COUNTRY VARCHAR(50) NOT NULL,
    PRIMARY KEY(CODE)
);

CREATE TABLE AIRPORTS (
	CODE CHAR(3) NOT NULL,
    NAME VARCHAR(20) NOT NULL,
    COUNTRY VARCHAR(50) NOT NULL,
    CITY VARCHAR(50) NOT NULL,
    PRIMARY KEY (CODE)
);

CREATE TABLE AIRPLANES (
	CODE CHAR(3) NOT NULL,
    TYPE VARCHAR(30) NOT NULL,
    SEATS INT NOT NULL,
    YEAR INT NOT NULL,
    PRIMARY KEY(CODE)
);

CREATE TABLE CUSTOMERS (
    ID INT AUTO_INCREMENT,
	FNAME VARCHAR(50) NOT NULL,
    LNAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50),
    PRIMARY KEY(ID)
);

CREATE TABLE AGENCIES (
	NAME VARCHAR(100) NOT NULL,
    COUNTRY VARCHAR(50) NOT NULL,
    CITY VARCHAR(50) NOT NULL,
    PHONE VARCHAR(50),
    PRIMARY KEY(NAME)
);

CREATE TABLE FLIGHTS (
	FNUMBER CHAR(10) NOT NULL,
    AIRLINE_OPERATOR CHAR(2) NOT NULL REFERENCES AIRLINES(CODE),
    DEP_AIRPORT CHAR(3) NOT NULL REFERENCES AIRPORTS(CODE),
    ARR_AIRPORT CHAR(3) NOT NULL REFERENCES AIRPORTS(CODE),
    FLIGHT_TIME TIME NOT NULL,
    FLIGHT_DURATION INT NOT NULL,
    AIRPLANE CHAR(3) NOT NULL REFERENCES AIRPLANES(CODE),
    PRIMARY KEY(FNUMBER),
    CONSTRAINT FK_FlightAirlineOperator FOREIGN KEY (AIRLINE_OPERATOR) REFERENCES AIRLINES(CODE),
    CONSTRAINT FK_FlightDEPAirport FOREIGN KEY (DEP_AIRPORT) REFERENCES AIRPORTS(CODE),
    CONSTRAINT FK_FlightARRAirport FOREIGN KEY (ARR_AIRPORT) REFERENCES AIRPORTS(CODE),
    CONSTRAINT FK_FlightAirplane FOREIGN KEY (AIRPLANE) REFERENCES AIRPLANES(CODE)
);

CREATE TABLE BOOKINGS (
	CODE CHAR(6) NOT NULL,
    AGENCY VARCHAR(100) NOT NULL REFERENCES AGENCIES(NAME),
    AIRLINE_CODE CHAR(2) NOT NULL REFERENCES AIRLINES(CODE),
    FLIGHT_NUMBER CHAR(10) NOT NULL REFERENCES FLIGHTS(FNUMBER),
    CUSTOMER_ID INT REFERENCES CUSTOMERS(ID),
    BOOKING_DATE DATE NOT NULL,
    FLIGHT_DATE DATE NOT NULL,
    PRICE DECIMAL(9,2) NOT NULL,
    STATUS INT NOT NULL,
    PRIMARY KEY(CODE),
    CONSTRAINT FK_BOOKING_AGENCY FOREIGN KEY (AGENCY) REFERENCES AGENCIES(NAME),
    CONSTRAINT FK_BOOKING_AIRLINE_CODE FOREIGN KEY (AIRLINE_CODE) REFERENCES AIRLINES(CODE),
    CONSTRAINT FK_BOOKING_FLIGHT_NUMBER FOREIGN KEY (FLIGHT_NUMBER) REFERENCES FLIGHTS(FNUMBER),
    CONSTRAINT FK_BOOKING_CUSTOMER_ID FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID)
);

ALTER TABLE airlines ADD UNIQUE(NAME);
ALTER TABLE airplanes ADD CONSTRAINT CHK_AirplaneSeats CHECK (airplanes.SEATS > 0);
ALTER TABLE bookings ADD CONSTRAINT CHK_BookingStatus CHECK (bookings.STATUS IN (0, 1));
ALTER TABLE flights ADD CONSTRAINT CHK_AirplaneSeats CHECK (flights.FLIGHT_DURATION > 0);